package com.idkedit.feature.timeline

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.idkedit.core.model.ProjectData

// 요청하신 파스텔 컬러 팔레트 정의
private val PastelBg = Color(0xFFFFF9F5)       // 부드러운 아이보리 바탕
private val PastelPreview = Color(0xFFE2F0D9)  // 연한 파스텔 연두
private val PastelCard = Color(0xFFFFF0F5)     // 연한 핑크
private val PastelAccent = Color(0xFFBAE1FF)   // 파스텔 하늘색
private val PastelBorder = Color(0xFFFFC6FF)   // 은은한 라벤더 보더
private val TextMain = Color(0xFF4A4A4A)       // 푹신한 다크 그레이 텍스트

@Composable
fun EditorScreen(
    projectData: ProjectData?,
        modifier: Modifier = Modifier
        ) {
            Column(
                    modifier = modifier
                                .fillMaxSize()
                                            .background(PastelBg)
                                                        .padding(16.dp)
                                                            ) {
                                                                    // 1. 파스텔 프리뷰 영역 (둥근 모서리 적용)
                                                                            Box(
                                                                                        modifier = Modifier
                                                                                                        .fillMaxWidth()
                                                                                                                        .weight(1f)
                                                                                                                                        .clip(RoundedCornerShape(24.dp))
                                                                                                                                                        .background(PastelPreview)
                                                                                                                                                                        .border(2.dp, PastelBorder, RoundedCornerShape(24.dp)),
                                                                                                                                                                                    contentAlignment = Alignment.Center
                                                                                                                                                                                            ) {
                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                        text = "✨ Preview Canvas ✨",
                                                                                                                                                                                                                                        fontSize = 16.sp,
                                                                                                                                                                                                                                                        fontWeight = FontWeight.Bold,
                                                                                                                                                                                                                                                                        color = TextMain
                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                    Spacer(modifier = Modifier.height(12.dp))

                                                                                                                                                                                                                                                                                                            // 2. 아기자기한 도구 모음 바 (둥근 캡슐 형태)
                                                                                                                                                                                                                                                                                                                    Row(
                                                                                                                                                                                                                                                                                                                                modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                .fillMaxWidth()
                                                                                                                                                                                                                                                                                                                                                                .height(56.dp)
                                                                                                                                                                                                                                                                                                                                                                                .clip(RoundedCornerShape(28.dp))
                                                                                                                                                                                                                                                                                                                                                                                                .background(PastelCard)
                                                                                                                                                                                                                                                                                                                                                                                                                .border(2.dp, PastelBorder, RoundedCornerShape(28.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                .padding(horizontal = 16.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                            horizontalArrangement = Arrangement.SpaceEvenly,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        verticalAlignment = Alignment.CenterVertically
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CuteToolButton(text = "▶ 재생")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CuteToolButton(text = "✂ 자르기")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CuteToolButton(text = "🎨 효과")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CuteToolButton(text = "🗑 삭제")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Spacer(modifier = Modifier.height(12.dp))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 3. 하단 타임라인 영역 (파스텔 카드 스타일)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Box(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .fillMaxWidth()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .weight(1f)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .clip(RoundedCornerShape(24.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .background(PastelCard)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .border(2.dp, PastelBorder, RoundedCornerShape(24.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .padding(16.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contentAlignment = Alignment.Center
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TimelineScreen(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            projectData = projectData,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxSize()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @Composable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private fun CuteToolButton(text: String) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Box(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                modifier = Modifier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .clip(RoundedCornerShape(16.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .background(PastelAccent)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .padding(horizontal = 12.dp, vertical = 6.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contentAlignment = Alignment.Center
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text = text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize = 16.sp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight = FontWeight.Medium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color = TextMain
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    